DROP DATABASE IF EXISTS `MikhailovIgor`;
CREATE DATABASE IF NOT EXISTS `MikhailovIgor`;
USE `MikhailovIgor`;

DROP TABLE IF EXISTS `product`;
CREATE TABLE IF NOT EXISTS `product`(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(128) NOT NULL,
    `cost` FLOAT NOT NULL
)ENGINE=INNODB;

DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user`(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `firstname` VARCHAR(128) NOT NULL,
    `email` VARCHAR(128) NOT NULL,
    `password` VARCHAR(128) NOT NULL,
    `date_created` INT NOT NULL
)ENGINE=INNODB;
